---
- name: Create an VM in Azure
  hosts: localhost #we are going to provision an vm
  connection: local 
  tasks:
  - name: Create a Resource Group in azure. 
    azurerm_rm_resourcegroup:
      name: myResourceGroup
      location: eastus